import pandas as pd

perfume = pd.read_csv('perfume_source.csv')

# notes to catogories mapping
perfume['main_accord1'] = perfume['main_accord1'].map({
    'citrus' : 'CITRUSSMELLS',
    'fruity' : 'FRUITSVEGETABLESANDNUTS',
    'coconut' : 'FRUITSVEGETABLESANDNUTS',
    'iris' : 'FLOWERS', 
    'floral' : 'FLOWERS', 
    'lavender' : 'FLOWERS', 
    'rose' : 'FLOWERS', 
    'violet' : 'FLOWERS',
    'white floral' : 'WHITEFLOWERS', 
    'yellow floral' : 'WHITEFLOWERS',
    'tobacco' : 'GREENSHERBSANDFOUGERES', 
    'green' : 'GREENSHERBSANDFOUGERES', 
    'aromatic' : 'GREENSHERBSANDFOUGERES',
    'warm spicy' : 'SPICES', 
    'vanilla' : 'SPICES', 
    'fresh spicy' : 'SPICES', 
    'soft spicy' : 'SPICES',
    'sweet' : 'SWEETSANDGOURMANDSMELLS',
    'woody' : 'WOODSANDMOSSES',
    'patchouli' : 'WOODSANDMOSSES', 
    'oud' : 'WOODSANDMOSSES', 
    'balsamic' : 'RESINSANDBALSAMS',
    'leather' : 'MUSKAMBERANIMALICSMELLS', 
    'amber' : 'MUSKAMBERANIMALICSMELLS', 
    'musky' :'MUSKAMBERANIMALICSMELLS', 
    'mossy' : 'MUSKAMBERANIMALICSMELLS', 
    'animalic' :'MUSKAMBERANIMALICSMELLS', 
    'lactonic' : 'MUSKAMBERANIMALICSMELLS',
    'ozonic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'aquatic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'powdery' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'smoky' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'earthy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'herbal' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'fresh' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'chocolate' : 'SWEETSANDGOURMANDSMELLS',
    'cherry' : 'FRUITSVEGETABLESANDNUTS',
    'tropical' : 'FRUITSVEGETABLESANDNUTS',
    'marine' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'salty' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'almond' : 'FRUITSVEGETABLESANDNUTS',
    'cinnamon' : 'SPICES',
    'coffee' :  'SPICES',
    'tuberose' : 'FLOWERS',
    'cacao' : 'SPICES',
    'coca-cola' : 'BEVERAGES',
    'honey' : 'SWEETSANDGOURMANDSMELLS',
    'caramel' : 'SWEETSANDGOURMANDSMELLS',
    'whiskey' : 'BEVERAGES',
    'aldehydic' : 'FLOWERS',
    'anis' : 'SPICES',
    'nutty' : 'FRUITSVEGETABLESANDNUTS',
    'savory' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'rum' : 'BEVERAGES',
    'soapy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'metallic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'wine' : 'BEVERAGES',
    'mineral' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'cannabis' : 'GREENSHERBSANDFOUGERES',
    'rubber' : 'RESINSANDBALSAMS',
    'sand' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'industrial glue' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'brown scotch tape' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'camphor' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'beeswax' : 'MUSKAMBERANIMALICSMELLS',
    'Champagne' : 'BEVERAGES',
    'vodka' : 'BEVERAGES',
    'sour' : 'FRUITSVEGETABLESANDNUTS',
    'asphault' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'paper' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'varnish' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'conifer' : 'FRUITSVEGETABLESANDNUTS',
    'hot iron' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'bitter' : 'GREENSHERBSANDFOUGERES',
    'alcohol' : 'BEVERAGES',
    'vinyl' : 'NATURALANDSYNTHETICPOPULARANDWEIRD'
})

perfume['main_accord2'] = perfume['main_accord2'].map({
    'citrus' : 'CITRUSSMELLS',
    'fruity' : 'FRUITSVEGETABLESANDNUTS',
    'coconut' : 'FRUITSVEGETABLESANDNUTS',
    'iris' : 'FLOWERS', 
    'floral' : 'FLOWERS', 
    'lavender' : 'FLOWERS', 
    'rose' : 'FLOWERS', 
    'violet' : 'FLOWERS',
    'white floral' : 'WHITEFLOWERS', 
    'yellow floral' : 'WHITEFLOWERS',
    'tobacco' : 'GREENSHERBSANDFOUGERES', 
    'green' : 'GREENSHERBSANDFOUGERES', 
    'aromatic' : 'GREENSHERBSANDFOUGERES',
    'warm spicy' : 'SPICES', 
    'vanilla' : 'SPICES', 
    'fresh spicy' : 'SPICES', 
    'soft spicy' : 'SPICES',
    'sweet' : 'SWEETSANDGOURMANDSMELLS',
    'woody' : 'WOODSANDMOSSES',
    'patchouli' : 'WOODSANDMOSSES', 
    'oud' : 'WOODSANDMOSSES', 
    'balsamic' : 'RESINSANDBALSAMS',
    'leather' : 'MUSKAMBERANIMALICSMELLS', 
    'amber' : 'MUSKAMBERANIMALICSMELLS', 
    'musky' :'MUSKAMBERANIMALICSMELLS', 
    'mossy' : 'MUSKAMBERANIMALICSMELLS', 
    'animalic' :'MUSKAMBERANIMALICSMELLS', 
    'lactonic' : 'MUSKAMBERANIMALICSMELLS',
    'ozonic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'aquatic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'powdery' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'smoky' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'earthy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'herbal' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'fresh' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'chocolate' : 'SWEETSANDGOURMANDSMELLS',
    'cherry' : 'FRUITSVEGETABLESANDNUTS',
    'tropical' : 'FRUITSVEGETABLESANDNUTS',
    'marine' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'salty' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'almond' : 'FRUITSVEGETABLESANDNUTS',
    'cinnamon' : 'SPICES',
    'coffee' :  'SPICES',
    'tuberose' : 'FLOWERS',
    'cacao' : 'SPICES',
    'coca-cola' : 'BEVERAGES',
    'honey' : 'SWEETSANDGOURMANDSMELLS',
    'caramel' : 'SWEETSANDGOURMANDSMELLS',
    'whiskey' : 'BEVERAGES',
    'aldehydic' : 'FLOWERS',
    'anis' : 'SPICES',
    'nutty' : 'FRUITSVEGETABLESANDNUTS',
    'savory' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'rum' : 'BEVERAGES',
    'soapy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'metallic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'wine' : 'BEVERAGES',
    'mineral' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'cannabis' : 'GREENSHERBSANDFOUGERES',
    'rubber' : 'RESINSANDBALSAMS',
    'sand' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'industrial glue' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'brown scotch tape' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'camphor' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'beeswax' : 'MUSKAMBERANIMALICSMELLS',
    'Champagne' : 'BEVERAGES',
    'vodka' : 'BEVERAGES',
    'sour' : 'FRUITSVEGETABLESANDNUTS',
    'asphault' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'paper' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'varnish' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'conifer' : 'FRUITSVEGETABLESANDNUTS',
    'hot iron' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'bitter' : 'GREENSHERBSANDFOUGERES',
    'alcohol' : 'BEVERAGES',
    'vinyl' : 'NATURALANDSYNTHETICPOPULARANDWEIRD'
})

perfume['main_accord3'] = perfume['main_accord3'].map({
    'citrus' : 'CITRUSSMELLS',
    'fruity' : 'FRUITSVEGETABLESANDNUTS',
    'coconut' : 'FRUITSVEGETABLESANDNUTS',
    'iris' : 'FLOWERS', 
    'floral' : 'FLOWERS', 
    'lavender' : 'FLOWERS', 
    'rose' : 'FLOWERS', 
    'violet' : 'FLOWERS',
    'white floral' : 'WHITEFLOWERS', 
    'yellow floral' : 'WHITEFLOWERS',
    'tobacco' : 'GREENSHERBSANDFOUGERES', 
    'green' : 'GREENSHERBSANDFOUGERES', 
    'aromatic' : 'GREENSHERBSANDFOUGERES',
    'warm spicy' : 'SPICES', 
    'vanilla' : 'SPICES', 
    'fresh spicy' : 'SPICES', 
    'soft spicy' : 'SPICES',
    'sweet' : 'SWEETSANDGOURMANDSMELLS',
    'woody' : 'WOODSANDMOSSES',
    'patchouli' : 'WOODSANDMOSSES', 
    'oud' : 'WOODSANDMOSSES', 
    'balsamic' : 'RESINSANDBALSAMS',
    'leather' : 'MUSKAMBERANIMALICSMELLS', 
    'amber' : 'MUSKAMBERANIMALICSMELLS', 
    'musky' :'MUSKAMBERANIMALICSMELLS', 
    'mossy' : 'MUSKAMBERANIMALICSMELLS', 
    'animalic' :'MUSKAMBERANIMALICSMELLS', 
    'lactonic' : 'MUSKAMBERANIMALICSMELLS',
    'ozonic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'aquatic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'powdery' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'smoky' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'earthy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'herbal' : 'NATURALANDSYNTHETICPOPULARANDWEIRD', 
    'fresh' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'chocolate' : 'SWEETSANDGOURMANDSMELLS',
    'cherry' : 'FRUITSVEGETABLESANDNUTS',
    'tropical' : 'FRUITSVEGETABLESANDNUTS',
    'marine' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'salty' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'almond' : 'FRUITSVEGETABLESANDNUTS',
    'cinnamon' : 'SPICES',
    'coffee' :  'SPICES',
    'tuberose' : 'FLOWERS',
    'cacao' : 'SPICES',
    'coca-cola' : 'BEVERAGES',
    'honey' : 'SWEETSANDGOURMANDSMELLS',
    'caramel' : 'SWEETSANDGOURMANDSMELLS',
    'whiskey' : 'BEVERAGES',
    'aldehydic' : 'FLOWERS',
    'anis' : 'SPICES',
    'nutty' : 'FRUITSVEGETABLESANDNUTS',
    'savory' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'rum' : 'BEVERAGES',
    'soapy' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'metallic' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'wine' : 'BEVERAGES',
    'mineral' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'cannabis' : 'GREENSHERBSANDFOUGERES',
    'rubber' : 'RESINSANDBALSAMS',
    'sand' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'industrial glue' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'brown scotch tape' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'camphor' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'beeswax' : 'MUSKAMBERANIMALICSMELLS',
    'Champagne' : 'BEVERAGES',
    'vodka' : 'BEVERAGES',
    'sour' : 'FRUITSVEGETABLESANDNUTS',
    'asphault' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'paper' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'varnish' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'conifer' : 'FRUITSVEGETABLESANDNUTS',
    'hot iron' : 'NATURALANDSYNTHETICPOPULARANDWEIRD',
    'bitter' : 'GREENSHERBSANDFOUGERES',
    'alcohol' : 'BEVERAGES',
    'vinyl' : 'NATURALANDSYNTHETICPOPULARANDWEIRD'
})
# perfume['brand_value'] = perfume['brand_value'].map({
#     'luxury' : 1.59,
#     'popular' : 1.06,
#     'normal' : 0.53
# })

# 걍 전처리하지 말고 애초에 mapping할 때 바꾸면 됨

# 중간 정도의 지속성도 moderate 중간 정도의 확산성도 moderate로 같기 때문에 실제 코사인 유사도를 계산할 때 벡터화 된 feature를 계산할 때 엉뚱한 결과를 나을 수 있음
# 따라서, 중간 정도의 지속성은 moderate, 중간 정도의 확선성은 medium으로 변경
# perfumes.loc[perfumes.sillage == 'moderate', ('sillage')] = 'medium'

# white flower => whiteflower
# perfumes.loc[perfumes.main_accord1 == 'WHITE FLOWERS', ('main_accord1')] = 'WHITEFLOWERS'
# perfumes.loc[perfumes.main_accord2 == 'WHITE FLOWERS', ('main_accord2')] = 'WHITEFLOWERS'

# drop unneeded column for cbf
perfume = perfume.drop(['brand', 'gender', 'launch_year', 'top_note', 'middle_note', 'base_note', 'day_or_night', 'sillage'], axis=1)
print(perfume)
perfume.to_csv("preprocessed_perfume_source.csv")



